### ISSUE TITLE
Utils

### ISSUE THREAD

**Issue by vzsoares** [vzsoares/DnD-dpr-Calculator#2]

**Comment by vzsoares** [comment]
![image](https://user-images.githubusercontent.com/86134825/178168542-844e5ddd-6182-45c1-aa31-96de2f072e40.png)

**Comment by lnunes13** [comment]
![d10](https://user-images.githubusercontent.com/60826550/178168694-d211d2d7-cdca-44b5-abd4-9e07d7bd3045.svg)
![d8](https://user-images.githubusercontent.com/60826550/178168696-89f6fd49-93b5-4ec4-bc52-47c48f8a7717.svg)
![d12](https://user-images.githubusercontent.com/60826550/178168697-be305987-7fc8-4095-86ab-98e21dde2ce2.svg)
![d6](https://user-images.githubusercontent.com/60826550/178168698-315b1c5f-1991-4481-a444-761daa851547.svg)
![d4](https://user-images.githubusercontent.com/60826550/178168699-bbec66d2-b14d-474e-b327-27800384d4b7.svg)
